/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Willian
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantallaDinamica = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCuentas = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuAdministracion = new javax.swing.JMenu();
        itemCatalogo = new javax.swing.JMenu();
        itemAgregarCatalogo = new javax.swing.JMenuItem();
        itemActualizarCatalogo = new javax.swing.JMenuItem();
        itemEliminarCatalogo = new javax.swing.JMenuItem();
        itemItems = new javax.swing.JMenu();
        itemAgregarItem = new javax.swing.JMenuItem();
        itemActualizarItem = new javax.swing.JMenuItem();
        itemEliminarItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pantallaDinamicaLayout = new javax.swing.GroupLayout(pantallaDinamica);
        pantallaDinamica.setLayout(pantallaDinamicaLayout);
        pantallaDinamicaLayout.setHorizontalGroup(
            pantallaDinamicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        pantallaDinamicaLayout.setVerticalGroup(
            pantallaDinamicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        getContentPane().add(pantallaDinamica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 570));

        jMenu1.setText("Funciones");
        jMenuBar1.add(jMenu1);

        menuCuentas.setText("Cuentas");

        jMenu3.setText("jMenu3");
        menuCuentas.add(jMenu3);

        jMenuBar1.add(menuCuentas);

        menuAdministracion.setText("Administración");

        itemCatalogo.setText("Catálogo");

        itemAgregarCatalogo.setText("Agregar catálogo");
        itemAgregarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarCatalogoActionPerformed(evt);
            }
        });
        itemCatalogo.add(itemAgregarCatalogo);

        itemActualizarCatalogo.setText("Actualizar catálogo");
        itemCatalogo.add(itemActualizarCatalogo);

        itemEliminarCatalogo.setText("Eliminar catálogo");
        itemCatalogo.add(itemEliminarCatalogo);

        menuAdministracion.add(itemCatalogo);

        itemItems.setText("Items");

        itemAgregarItem.setText("Agregar item");
        itemItems.add(itemAgregarItem);

        itemActualizarItem.setText("Actualizar item");
        itemItems.add(itemActualizarItem);

        itemEliminarItem.setText("Eliminar item");
        itemItems.add(itemEliminarItem);

        menuAdministracion.add(itemItems);

        jMenuBar1.add(menuAdministracion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAgregarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarCatalogoActionPerformed
        IntFrmAgregarCatalogo intFrmAgregarCatalogo = new IntFrmAgregarCatalogo();
        pantallaDinamica.add(intFrmAgregarCatalogo);
        intFrmAgregarCatalogo.setVisible(true);
        intFrmAgregarCatalogo.setIconifiable(true);
        intFrmAgregarCatalogo.setClosable(true);
    }//GEN-LAST:event_itemAgregarCatalogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemActualizarCatalogo;
    private javax.swing.JMenuItem itemActualizarItem;
    private javax.swing.JMenuItem itemAgregarCatalogo;
    private javax.swing.JMenuItem itemAgregarItem;
    private javax.swing.JMenu itemCatalogo;
    private javax.swing.JMenuItem itemEliminarCatalogo;
    private javax.swing.JMenuItem itemEliminarItem;
    private javax.swing.JMenu itemItems;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenu menuCuentas;
    private javax.swing.JDesktopPane pantallaDinamica;
    // End of variables declaration//GEN-END:variables
}
